"""create tables Animals, Zookeeper, Enclosure

Revision ID: 12935ef1b661
Revises: 
Create Date: 2023-09-19 08:06:45.268387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12935ef1b661'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zookeepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zookeepers')
    op.drop_table('enclosures')
    op.drop_table('animals')
    # ### end Alembic commands ###
