"""Add foreign key in Animal model

Revision ID: 32e239c98953
Revises: 12935ef1b661
Create Date: 2023-09-19 11:37:49.562519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e239c98953'
down_revision = '12935ef1b661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enclosure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=255), nullable=True),
    sa.Column('open_to_visitors', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zookeeper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('species', sa.String(length=255), nullable=True),
    sa.Column('zookeeper_id', sa.Integer(), nullable=True),
    sa.Column('enclosure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enclosure_id'], ['enclosure.id'], ),
    sa.ForeignKeyConstraint(['zookeeper_id'], ['zookeeper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('enclosures')
    op.drop_table('animals')
    op.drop_table('zookeepers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zookeepers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enclosures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('animal')
    op.drop_table('zookeeper')
    op.drop_table('enclosure')
    # ### end Alembic commands ###
